plugins {
    id 'net.neoforged.moddev' version '2.0.107' apply false
}

subprojects {
    group = rootProject.mod_group_id
    version = rootProject.mod_version

    apply plugin: 'java-library'

    java.toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version as int)

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}
